#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"
TYPE_TOTAL="${BLOCK_INSTANCE:-total}"
function memparse {
  awk -v type=$1 '
  /^MemTotal:/ {
	  mem_total=$2
  }
  /^MemFree:/ {
  	mem_free=$2
  }
  /^Buffers:/ {
  	mem_free+=$2
  }
  /^Cached:/ {
  	mem_free+=$2
  }
  /^SwapTotal:/ {
  	swap_total=$2
  }
  /^SwapFree:/ {
  	swap_free=$2
  }
  END {
  	if (type == "swap")
  		printf("%.1f\n", (swap_total-swap_free)/1024)
    else if(type == "mem")
      printf("%.1f\n", (mem_total-mem_free)/1024)
    else if(type == "total")
      printf("%.1f\n", (mem_total)/1024)
    else
  		printf("%.1f\n", mem_free/1024)
  }
' /proc/meminfo
}
# Print out the awk result to a variable
MEM=$(memparse $TYPE)
MEM_WARNING=$(bc <<< "$(memparse $TYPE_TOTAL)*.75")
echo "${MEM}Mb"
echo "${MEM}Mb"

if (( $(bc <<< "$MEM < $MEM_WARNING") == 1 )) 
then
  echo "#cccccc"
else
  echo "#ffffff"
fi 
