#!/bin/sh

INTERFACE="${BLOCK_INSTANCE:-wlp3s0}"

state="$(cat /sys/class/net/$INTERFACE/operstate)"


if [ "$state" != "up" ]; then
	echo " -"
	echo " -"
  echo"#cccccc"
	exit 0
fi

echo " $(iwgetid -r)"
echo " $(iwgetid -r)"
echo "#ffffff"

