#!/bin/bash
source $(dirname $0)/config

CAPACITY="$(cat /sys/class/power_supply/BAT0/capacity)"
STATUS="$(cat /sys/class/power_supply/BAT0/status)"

if [ "$STATUS" = "Discharging" ]; then
  echo -n "$CAPACITY%% $DIV"
elif [ $CAPACITY -lt 40 ]; then
  echo -n "$(F $CAPACITY%% $RED) $DIV"
else
  echo -n "$(F $CAPACITY%% $GREEN) $DIV"
fi

