#! /bin/bash
VOLUME=$(pamixer --get-volume)
MUTE=$(pamixer --get-mute)


if [ "$MUTE" = "true" ]; then
  echo   $VOLUME%
  echo   $VOLUME%
  echo "#ffffff"
else
  echo   $VOLUME%
  echo   $VOLUME%
  echo "#cccccc"
fi
